# -- coding: utf-8 --
{
    'name': 'eSMIS Admission',
    'version': '16.0.1.0.0',
    'summary': 'Manage Students Admission',
    'description': """
        Helps you to manage Students Admission.
        """,
    'category': 'Generic Modules/Human Resources',
    'author': "NexBridgetech inc.",
    'company': 'NexBridgetech inc.',
    'maintainer': 'NexBridgetech inc.',
    'website': "https://nexbridgetech.com/",
    'depends': [
        'base', 'base_address_extended', 'mail', 'esmis_base', 'muk_web_theme', 'calendar'
    ],
    'data': [
        'security/esmis_admission_security.xml',
        'security/ir.model.access.csv',
        'report/admission_student_application_form_action.xml',
        'report/admission_student_application_form_template.xml',
        'report/admission_student_test_results.xml',
        'report/student_cog.xml',
        'report/cumulative_quality_gpa.xml',
        'report/academic_program_evaluation.xml',
        'report/certification_of_latin_honors.xml',
        'report/cav_report.xml',
        'data/actions.xml',
        'data/data.xml',
        'data/mail_templates.xml',
        'views/esmis_admission.xml',
        # 'views/esmis_admission_guidance.xml',
        'views/esmis_students.xml',
        'views/esmis_test_schedule.xml',
        'views/esmis_admission_test_type.xml',
        'views/res_users.xml',
        'views/admission_require_attachment.xml',
        'views/res_config_settings.xml',
        'views/mail_mail_views.xml',
        'views/calendar_event_view.xml',
        'views/esmis_sms_announcement_view.xml',
        'views/esmis_signatories.xml',
        'wizards/admission_exam_scheduling_wiz.xml',
        'wizards/admission_not_qualified_wiz.xml',
        'wizards/confirm_with_password_wiz.xml',
        'wizards/admission_send_email.xml',
        'wizards/admission_update_selected_courses.xml',
        'wizards/student_cog_wiz.xml',
        'wizards/certification_latin_honor_wiz.xml',
        'wizards/cav_wiz.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
