# Part of eSMIS App. See LICENSE file for full copyright and licensing details.
{
    "name": "eSMIS Curriculum",
    "category": "eSMIS",
    "version": "16.0.0.0.1",
    "sequence": 1,
    "author": "Pith Technologies",
    "website": "https://pithtech.net",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["gonzalesedwin1123","michaelgonzales"],
    "depends": ["base", "esmis_base", "esmis_enrollment"],
    "data": [
        "security/ir.model.access.csv",
        "data/iso_printouts.xml",
        "views/curriculum_view.xml",
        "views/sections_view.xml",
        "views/enrollment_view.xml",
        "views/subject_offerings_view.xml",
        "wizards/assign_to_section_wizard.xml",
        "reports/paper_format.xml",
        "reports/curriculum_report.xml",
        "reports/enrollment_report.xml",
        "reports/certificate_of_registration.xml",
        "reports/bulk_cor.xml",
        # "reports/bulk_cor_copy.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
