# Part of eSMIS App. See LICENSE file for full copyright and licensing details.
{
    "name": "eSMIS Enrollment",
    "category": "eSMIS",
    "version": "16.0.0.0.1",
    "sequence": 1,
    "author": "Pith Technologies",
    "website": "https://pithtech.net",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["gonzalesedwin1123","michaelgonzales"],
    "depends": ["base", "esmis_base"],
    "data": [
        "security/esmis_enrollment_security.xml",
        "security/ir.model.access.csv",
        "data/enrollment_sequence_data.xml",
        'data/mail_templates.xml',
        'data/actions.xml',
        "views/menu_view.xml",
        # "views/student_view.xml",
        "views/enrollments_view.xml",
        "views/esmis_student.xml",
        # "views/config_view.xml",
        'views/res_config_settings.xml',
        "wizards/enrollment_send_email.xml",
        "reports/paper_format.xml",
        "reports/enrollment_report.xml",

    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
